# Generated by Django 4.1.7 on 2023-03-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='gender',
            field=models.CharField(choices=[(None, 'Choose an option: '), ('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
