# Generated by Django 4.1.7 on 2023-03-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_alter_information_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='information',
        ),
    ]
