# Generated by Django 4.1.7 on 2023-03-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz_app', '0003_delete_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[(None, 'Choose an option: '), ('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.CharField(max_length=1)),
                ('educational_background', models.CharField(default=0, max_length=1)),
                ('occupation', models.CharField(max_length=1)),
                ('location', models.CharField(max_length=1)),
                ('marital_status', models.CharField(max_length=1)),
                ('individual_income', models.CharField(max_length=1)),
                ('family_income', models.CharField(max_length=1)),
            ],
        ),
    ]
