# Generated by Django 4.1.7 on 2023-03-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='tech_q1',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='tech_q2',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='tech_q3',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='tech_q4',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='tech_q5',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
