# Generated by Django 4.1.7 on 2023-03-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_information_tech_q1_information_tech_q2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='curr_q1',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='curr_q2',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='curr_q3',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='curr_q4',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='curr_q5',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
