# Generated by Django 4.1.7 on 2023-03-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_information_curr_q1_information_curr_q2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='plac_q1',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='plac_q2',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='plac_q3',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='plac_q4',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='plac_q5',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='sch_q1',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='sch_q2',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='sch_q3',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='sch_q4',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='sch_q5',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='sec_q1',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='sec_q2',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='sec_q3',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='sec_q4',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='sec_q5',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
