# Generated by Django 4.1.7 on 2023-03-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_information_plac_q1_information_plac_q2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
